/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTemplateLibraryRouteImport } from './routes/_authenticated.template-library'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated.preferences'
import { Route as AuthenticatedLinkedinProfileRouteImport } from './routes/_authenticated.linkedin-profile'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated.connections'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplateLibraryRoute =
  AuthenticatedTemplateLibraryRouteImport.update({
    id: '/template-library',
    path: '/template-library',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLinkedinProfileRoute =
  AuthenticatedLinkedinProfileRouteImport.update({
    id: '/linkedin-profile',
    path: '/linkedin-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/linkedin-profile': typeof AuthenticatedLinkedinProfileRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/template-library': typeof AuthenticatedTemplateLibraryRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/linkedin-profile': typeof AuthenticatedLinkedinProfileRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/template-library': typeof AuthenticatedTemplateLibraryRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/linkedin-profile': typeof AuthenticatedLinkedinProfileRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/template-library': typeof AuthenticatedTemplateLibraryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connections'
    | '/linkedin-profile'
    | '/preferences'
    | '/template-library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/connections'
    | '/linkedin-profile'
    | '/preferences'
    | '/template-library'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/connections'
    | '/_authenticated/linkedin-profile'
    | '/_authenticated/preferences'
    | '/_authenticated/template-library'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/template-library': {
      id: '/_authenticated/template-library'
      path: '/template-library'
      fullPath: '/template-library'
      preLoaderRoute: typeof AuthenticatedTemplateLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/linkedin-profile': {
      id: '/_authenticated/linkedin-profile'
      path: '/linkedin-profile'
      fullPath: '/linkedin-profile'
      preLoaderRoute: typeof AuthenticatedLinkedinProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedLinkedinProfileRoute: typeof AuthenticatedLinkedinProfileRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedTemplateLibraryRoute: typeof AuthenticatedTemplateLibraryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedLinkedinProfileRoute: AuthenticatedLinkedinProfileRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedTemplateLibraryRoute: AuthenticatedTemplateLibraryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
